# Generated by Django 2.1.7 on 2019-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idk', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=49)),
                ('desc', models.TextField()),
            ],
        ),
    ]
